#!/bin/bash
if [ ! -f ~/.cgenierc ]; then
    echo 'GENIE not set up: run the setup-cgenie script!'
    exit 0
fi
cgenie_root=`grep cgenie_root ~/.cgenierc | cut -d: -f2 | sed -e 's/^ *//'`
source $cgenie_root/tools/find_python
exec $PYTHON $cgenie_root/tools/cgenie-gui.py $*
