#!/bin/bash
if [ ! -f ~/.ctoasterrc ]; then
    echo 'cTOASTER not set up: run the setup-ctoaster script!'
    exit 0
fi
ctoaster_root=`grep ctoaster_root ~/.ctoasterrc | cut -d: -f2 | sed -e 's/^ *//'`
source $ctoaster_root/tools/find_python
exec $PYTHON $ctoaster_root/tools/coverage.py $*
