#!/bin/bash
if [ ! -f ~/.ctoasterrc ]; then
    echo 'cTOASTER not set up: run the setup-ctoaster script!'
    exit 0
fi
ctoaster_root=`grep ctoaster_root ~/.ctoasterrc | cut -d: -f2 | sed -e 's/^ *//'`
# Removed the line that sources find_python script
exec python3 $ctoaster_root/tools/coverage.py $*