#!/bin/bash
if [ -f ~/.cgenierc ]; then
    echo 'GENIE already set up -- if you want to start over, remove ~/.cgenierc'
    exit 0
fi
#source tools/find_python
export python=/usr/bin/python3
exec $python tools/setup-cgenie.py

