#!/bin/bash

if [ -z $cgenie_root ]; then
    echo "SOMETHING IS WRONG: cgenie_root NOT SET IN find_python"
    exit 1
fi

if [ -z "$ANACONDA_DIR" ]; then
    echo 'ANACONDA_DIR environment variable not set!'
    echo
    echo 'GENIE relies on the Anaconda Python installation.'
    echo 'You can find this at https://store.continuum.io/cshop/anaconda/'
    echo
    echo 'Please install Anaconda and set the ANACONDA_DIR environment'
    echo 'variable to point to the Anaconda installation directory.'
    exit 0
fi

export PYTHON=$ANACONDA_DIR/bin/python
