#!/usr/bin/env python2

from __future__ import print_function
import sys

excs = { 'ents_1': 'ents_indir_name',
         'ents_2': 'ents_outdir_name',
         'ents_config': 'ents_condir_name',
         'ents_grid': 'ents_igrid',
         'ents_3': 'ents_npstp',
         'ents_4': 'ents_iwstp',
         'ents_5': 'ents_itstp',
         'ents_6': 'ents_ianav',
         'ents_7': 'ents_restart',
         'ents_8': 'ents_yearlen',
         'ents_17': 'ents_out_name',
         'ents_18': 'ents_netin',
         'ents_19': 'ents_netout',
         'ents_20': 'ents_ascout',
         'ents_21': 'ents_filenetin',
         'ents_22': 'ents_dirnetout',
         'ents_24': 'ents_restart_file',
         'ents_25': 'ents_offlineswitch',
         'go_1': 'go_indir_name',
         'go_2': 'go_outdir_name',
         'go_grid': 'go_igrid',
         'go_topo': 'go_world',
         'go_3': 'go_npstp',
         'go_4': 'go_iwstp',
         'go_5': 'go_itstp',
         'go_6': 'go_ianav',
         'go_6b': 'go_conserv_per',
         'go_7': 'go_ans',
         'go_8': 'go_yearlen',
         'go_9': 'go_nyear',
         'go_10': 'go_temp0',
         'go_11': 'go_temp1',
         'go_12': 'go_rel',
         'go_13': 'go_scf',
         'go_14': 'go_diff_1',
         'go_15': 'go_diff_2',
         'go_16': 'go_adrag',
         'go_fwanom': 'go_fwanomin',
         'go_fwanomfile': 'go_cmip_model',
         'go_albedo': 'go_albocn',
         'go_ocnconv': 'go_iconv',
         'go_Tdata': 'go_tdatafile',
         'go_Sdata': 'go_sdatafile',
         'go_17': 'go_lout',
         'go_18': 'go_netin',
         'go_19': 'go_netout',
         'go_20': 'go_ascout',
         'go_21': 'go_filenetin',
         'go_22': 'go_dirnetout',
         'go_23': 'go_lin',
         'ea_1': 'ea_indir_name',
         'ea_2': 'ea_outdir_name',
         'ea_grid': 'ea_igrid',
         'ea_topo': 'ea_world',
         'ea_taux_u': 'ea_xu_wstress',
         'ea_tauy_u': 'ea_yu_wstress',
         'ea_taux_v': 'ea_xv_wstress',
         'ea_tauy_v': 'ea_yv_wstress',
         'ea_adv_u': 'ea_u_wspeed',
         'ea_adv_v': 'ea_v_wspeed',
         'ea_3': 'ea_npstp',
         'ea_4': 'ea_iwstp',
         'ea_5': 'ea_itstp',
         'ea_6': 'ea_ianav',
         'ea_7': 'ea_ans',
         'ea_8': 'ea_yearlen',
         'ea_9': 'ea_nyear',
         'ea_10': 'ea_ndta',
         'ea_11': 'ea_scf',
         'ea_12': 'ea_diffamp_1',
         'ea_13': 'ea_diffamp_2',
         'ea_14': 'ea_diffwid',
         'ea_15': 'ea_difflin',
         'ea_16': 'ea_betaz_1',
         'ea_18': 'ea_betaz_2',
         'ea_17': 'ea_betam_1',
         'ea_19': 'ea_betam_2',
         'ea_22': 'ea_tatm',
         'ea_23': 'ea_relh0_ocean',
         'ea_24': 'ea_relh0_land',
         'ea_25': 'ea_extra1a',
         'ea_26': 'ea_extra1b',
         'ea_27': 'ea_extra1c',
         'ea_28': 'ea_scl_fwf',
         'ea_Tdata': 'ea_tdatafile',
         'ea_Hdata': 'ea_qdatafile',
         'ea_29': 'ea_lout',
         'ea_30': 'ea_netin',
         'ea_31': 'ea_netout',
         'ea_32': 'ea_ascout',
         'ea_33': 'ea_filenetin',
         'ea_34': 'ea_dirnetout',
         'ea_35': 'ea_lin',
         'ea_36': 'ea_atchem_radfor',
         'olr_adj0': 'ea_olr_adj0',
         'ea_37': 'ea_ents_radfor',
         'ea_38': 'ea_orbit_radfor',
         'ea_39': 'ea_t_orbit',
         'ea_40': 'ea_norbit',
         'ea_41': 'ea_orbitsteps',
         'ea_42': 'ea_filenameorbit',
         'gs_1': 'gs_indir_name',
         'gs_2': 'gs_outdir_name',
         'gs_grid': 'gs_igrid',
         'gs_topo': 'gs_world',
         'gs_3': 'gs_npstp',
         'gs_4': 'gs_iwstp',
         'gs_5': 'gs_itstp',
         'gs_6': 'gs_ianav',
         'gs_6b': 'gs_conserv_per',
         'gs_7': 'gs_ans',
         'gs_8': 'gs_yearlen',
         'gs_9': 'gs_nyear',
         'gs_11': 'gs_diffsic',
         'gs_12': 'gs_lout',
         'gs_13': 'gs_netin',
         'gs_14': 'gs_netout',
         'gs_15': 'gs_ascout',
         'gs_16': 'gs_filenetin',
         'gs_17': 'gs_dirnetout',
         'gs_18': 'gs_lin' }

if len(sys.argv) != 2: sys.exit('Usage: fix-exceptions.py <infile>')

with open(sys.argv[1]) as fp:
    for lin in fp:
        ws = lin.split('=')
        if len(ws) > 1 and ws[0] in excs:
            ws[0] = excs[ws[0]]
        lout = '='.join(ws)
        print(lout, end='')
