#!/bin/bash
root=`pwd`
echo "ctoaster_root: ${root}" > ~/.ctoasterrc
echo "ctoaster_data: ${root/ctoaster/ctoaster-data}" >> ~/.ctoasterrc
echo "ctoaster_test: ${root/ctoaster/ctoaster-test}" >> ~/.ctoasterrc
echo "ctoaster_jobs: ${root/ctoaster/ctoaster-jobs}" >> ~/.ctoasterrc
echo "ctoaster_version: DEVELOPMENT" >> ~/.ctoasterrc
