import os, os.path
import platform as P

Import('env', 'subdirs', 'build_type')
Export('env')

allobjs = []
allsrcs = []
for sd in subdirs:
    consFile = os.path.join(sd, 'SConscript')
    res = env.SConscript(consFile)
    allobjs += res['objs']
    allsrcs += res['srcs']
allsrcs = list(map(str, Glob('genie.f90'))) + list(map(str, allsrcs))

###print(allobjs)

Execute(Mkdir(subdirs))

objs = list(filter(lambda o: str(o)[-4:] != '.mod', allobjs))

###print(objs)

env.Program('nccompare.exe', [os.path.join('tools', 'nccompare.f90')])

###print('***')

if P.system() != 'Windows':
    env.Program('genie.exe', ['genie.f90'] + objs)
else:
    if build_type == 'debug': env.Replace(PDB='genie-debug.pdb')
    exe = env.Program('genie.exe', ['genie.f90'] + objs)
    if len(exe) > 1: exe = exe[0]
    var = 'Debug' if build_type == 'debug' else 'Release'
    env.MSVSProject(target = 'cgenie-scons' + env['MSVSPROJECTSUFFIX'],
                    srcs = allsrcs,
                    buildtarget = exe,
                    variant = var)
